[versions]
spring-boot = "3.4.2"
spring-dependency-management = "1.1.7"
ktlint = "12.1.2"
kotlin = "2.0.21"
mysql = "9.2.0"
jackson = "2.18.2"
thumbnailator = "0.4.20"

[libraries.spring-boot-starter-data-jpa]
module = "org.springframework.boot:spring-boot-starter-data-jpa"

[libraries.spring-boot-starter-web]
module = "org.springframework.boot:spring-boot-starter-web"

[libraries.spring-boot-starter-validation]
module = "org.springframework.boot:spring-boot-starter-validation"

[libraries.spring-boot-starter-security]
module = "org.springframework.boot:spring-boot-starter-security"

[libraries.spring-boot-starter-oauth2-client]
module = "org.springframework.boot:spring-boot-starter-oauth2-client"

[libraries.spring-boot-starter-oauth2-resource-server]
module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server"

[libraries.spring-boot-starter-actuator]
module = "org.springframework.boot:spring-boot-starter-actuator"

[libraries.spring-boot-devtools]
module = "org.springframework.boot:spring-boot-devtools"

[libraries.spring-boot-starter-test]
module = "org.springframework.boot:spring-boot-starter-test"

[libraries.kotlin-reflect]
module = "org.jetbrains.kotlin:kotlin-reflect"
version.ref = "kotlin"

[libraries.kotlin-stdlib]
module = "org.jetbrains.kotlin:kotlin-stdlib"
version.ref = "kotlin"

[libraries.kotlin-allopen]
module = "org.jetbrains.kotlin:kotlin-allopen"
version.ref = "kotlin"

[libraries.kotlin-test]
module = "org.jetbrains.kotlin:kotlin-test"
version.ref = "kotlin"

[libraries.jackson-module-kotlin]
module = "com.fasterxml.jackson.module:jackson-module-kotlin"
version.ref = "jackson"

[libraries.mysql-connector-j]
module = "com.mysql:mysql-connector-j"
version.ref = "mysql"

[libraries.thumbnailator]
module = "net.coobird:thumbnailator"
version.ref = "thumbnailator"

[plugins]
spring-boot = {id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management = {id = "io.spring.dependency-management", version.ref = "spring-dependency-management"}
ktlint = {id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint"}
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-jpa = {id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin"}
kotlin-spring = {id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin"}
jacoco = {id = "jacoco"}