package com.dugaza.letsdrive.exception

import org.springframework.http.HttpStatus

enum class ErrorCode(
    val status: HttpStatus,
    val code: String,
) {
    // File Error
    FILE_SIZE_TOO_LARGE(HttpStatus.BAD_REQUEST, "FILE.001"),
    INVALID_EXTENSION(HttpStatus.BAD_REQUEST, "FILE.002"),
    IMAGE_THUMBNAIL_GENERATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE.003"),
    FILE_COMPRESSION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE.004"),
    FILE_DECOMPRESSION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "FILE.005"),
    NOT_FOUND_FILE_DETAIL(HttpStatus.NOT_FOUND, "FILE.006"),
    INVALID_IMAGE_DATA(HttpStatus.BAD_REQUEST, "FILE.007"),
    NOT_FOUND_FILE_MASTER(HttpStatus.NOT_FOUND, "FILE.008"),
    INVALID_DISPOSITION_TYPE(HttpStatus.BAD_REQUEST, "FILE.009"),

    // User Error
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER.001"),
    UNSUPPORTED_AUTH_PROVIDER(HttpStatus.BAD_REQUEST, "USER.002"),
    EMAIL_DUPLICATION(HttpStatus.BAD_REQUEST, "USER.003"),

    // System Error
    INVALID_ERROR_CODE(HttpStatus.BAD_REQUEST, "SYSTEM.001"),

    // Validation
    DEFAULT_VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "VALID.001"),
    DEFAULT_NOT_NULL_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.002"),
    DEFAULT_NOT_BLANK_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.003"),
    DEFAULT_SIZE_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.004"),
    DEFAULT_MIN_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.005"),
    DEFAULT_MAX_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.006"),
    DEFAULT_RANGE_MESSAGE(HttpStatus.BAD_REQUEST, "VALID.007"),

    // Auth Error
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH_001"),
    INVALID_DEVICE_ID(HttpStatus.BAD_REQUEST, "AUTH_002"),

    // For test
    FOO(HttpStatus.INTERNAL_SERVER_ERROR, "FOO.001"),
}
